name: Cypress Tests

on: push

jobs:
  cypress-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Cypress Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
          if-no-files-found: ignore

  cypress-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Cypress Tests in Firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-firefox
          path: cypress/videos
          if-no-files-found: ignore

  cypress-edge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Cypress Tests in Edge
        uses: cypress-io/github-action@v6
        with:
          browser: edge
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-edge
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-edge
          path: cypress/videos
          if-no-files-found: ignore
